default_language_version:
  python: python3.13

repos:
  # -----------------------------
  # Ruff: lint + format (core)
  # -----------------------------
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.10
  hooks:
  - id: ruff
    name: ruff (lint)
    args:
    - --fix
    - --exit-non-zero-on-fix
    types_or: [python]

  - id: ruff-format
    name: ruff (format)
    types_or: [python]


  # -----------------------------
  # General hygiene
  # -----------------------------
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
    args: ["--maxkb=2048"]
  - id: check-merge-conflict

      # YAML matters for Hydra
  - id: check-yaml
    args: ["--allow-multiple-documents"]

  # -----------------------------
  # YAML formatting (Hydra-friendly)
  # -----------------------------
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.15.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --indent=2
    - --preserve-quotes
    files: \.(yml|yaml)$

# Could add mypy for type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.19.1
  hooks:
  - id: mypy